name: CI

on:
  push:
    branches:
      - login+playlist
  pull_request:
    branches:
      - login+playlist

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build app
        run: npm run build
